In [ ]:
df['prediction_time'] = pd.to_datetime(df['prediction_time'], format='%Y-%m-%d %H-%M-%S')
df = df.assign(
    year=df['prediction_time'].dt.year,
    month=df['prediction_time'].dt.month,
    day=df['prediction_time'].dt.day,
    hour=df['prediction_time'].dt.hour,
    minute=df['prediction_time'].dt.minute,
    second=df['prediction_time'].dt.second
)
{
    "cells": [
        {
            "cell_type": "code",
            "id": "#VSC-f9955adc",
            "metadata": {
                "language": "python"
            },
            "source": [
                "import pandas as pd",
                "import numpy as np",
                "import matplotlib.pyplot as plt"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-d1535be9",
            "metadata": {
                "language": "python"
            },
            "source": [
                "df = pd.read_csv('train.csv', index_col='user_id')",
                "df.drop(columns=['ID'], inplace=True)",
                "df.head()"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-38d1f4a8",
            "metadata": {
                "language": "python"
            },
            "source": [
                "df.info()"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-2aef85e2",
            "metadata": {
                "language": "python"
            },
            "source": [
                "df.shape"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-0d369824",
            "metadata": {
                "language": "python"
            },
            "source": [
                "df.isnull().sum()"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-1d4e0847",
            "metadata": {
                "language": "python"
            },
            "source": [
                "for col in df.columns:",
                "    unique_columns = df[col].unique()",
                "    print(f\"Unique values in colums {col}: is {len(unique_columns)}\")",
                "    print(unique_columns)"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-11e9a49e",
            "metadata": {
                "language": "python"
            },
            "source": [
                "missing_columns = df.columns[df.isnull().any()].to_list()",
                "for col in missing_columns:",
                "    df[f\"{col}_missing\"] = df[col].isnull().astype(int)",
                "    df[col] = df[col].fillna(\"missing\")",
                "df.head()"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-9b118027",
            "metadata": {
                "language": "python"
            },
            "source": [
                "df.isnull().any().any()"
            ]
        },
        {
            "cell_type": "code",
            "id": "#VSC-c0dc380a",
            "metadata": {
                "language": "python"
            },
            "source": [
                ""
            ]
        }
    ]
}

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df = pd.read_csv('train.csv', index_col='user_id')
df.drop(columns=['ID'], inplace=True)
df.head()

,confidence,predicted_intensity,community,district,prediction_time,indicator,indicator_description,time_observed,Target,forecast_length
user_id,,,,,,,,,,
11,0.3,0.0,Tumfa,atiwa_west,2025-05-30 11:09:33,NaN,NaN,NaN,MEDIUMRAIN,12
17,0.3,0.0,Kwabeng,atiwa_west,2025-05-30 11:09:35,NaN,NaN,NaN,HEAVYRAIN,12
19,0.3,0.0,Akropong,atiwa_west,2025-05-30 11:09:47,NaN,NaN,NaN,MEDIUMRAIN,12
23,0.3,0.0,Asamama,atiwa_west,2025-05-30 11:16:33,NaN,NaN,NaN,HEAVYRAIN,12
23,0.3,0.0,Asamama,atiwa_west,2025-05-30 11:16:55,NaN,NaN,NaN,HEAVYRAIN,12

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10928 entries, 11 to 77
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   confidence             10928 non-null  float64
 1   predicted_intensity    10928 non-null  float64
 2   community              10928 non-null  object
 3   district               10928 non-null  object
 4   prediction_time        10928 non-null  object
 5   indicator              503 non-null    object
 6   indicator_description  346 non-null    object
 7   time_observed          72 non-null     object
 8   Target                 10928 non-null  object
 9   forecast_length        10928 non-null  int64
dtypes: float64(2), int64(1), object(7)
memory usage: 939.1+ KB

In [16]:
df.shape

(10928, 10)

In [17]:
df.isnull().sum()

confidence                   0
predicted_intensity          0
community                    0
district                     0
prediction_time              0
indicator                10425
indicator_description    10582
time_observed            10856
Target                       0
forecast_length              0
dtype: int64

In [18]:
for col in df.columns:
    unique_columns = df[col].unique()
    print(f"Unique values in colums {col}: is {len(unique_columns)}")
    print(unique_columns)

Unique values in colums confidence: is 3
[0.3 0.6 1. ]
Unique values in colums predicted_intensity: is 4
[0.   0.66 0.33 1.  ]
Unique values in colums community: is 38
['Tumfa ' 'Kwabeng ' 'Akropong' 'Asamama' 'Akwaduuso ' 'akwaduuso  '
 'Banso ' 'Akropong ' 'Awenare' 'mouso ' 'Abomosu ' 'Foso Odumasi '
 'Amonom ' 'Asunafo ' 'Apampatia ' 'Tumfa' 'FOSO ODUMASI ' 'asunafo'
 'Assin ATONSU ' 'odumasi ' ' Assin Wurakese' 'Akwaduuso' 'Assin Atonsu '
 'odumasi  Adansi' 'Apampatia' 'Assin Aponsie ' 'Assin nyankomasi '
 'Assin Foso Odumasi' 'akwaduuso ' 'assin mesre nyame ' 'Asunafo'
 'ASSIN BROFOYEDUR' 'Mampamhwe' 'Atonsu' 'odumasi' 'Assin Nyankomasi'
 'Assin Aponsie' 'Assin  Aponsie']
Unique values in colums district: is 3
['atiwa_west' 'assin_fosu' 'obuasi_east']
Unique values in colums prediction_time: is 10887
['2025-05-30 11:09:33' '2025-05-30 11:09:35' '2025-05-30 11:09:47' ...
 '2025-07-20 19:13:21' '2025-07-20 19:18:39' '2025-07-20 19:23:03']
Unique values in colums indicator: is 11
[nan 'heat' 'sun' 'clouds' 'wind' 'dew' 'fog' 'star' 'thunder' 'moon'
 'lightning']
Unique values in colums indicator_description: is 29
[nan 'Gathering of clouds in the east' 'Light fog'
 'Heavy Clouds (probably cumulus) reflecting rays of sunlight'
 'Sunny afternoon' 'Clouds moving South → East'
 'Fast-moving Cirrus clouds (white, visible at dawn)' 'Heated atmosphere'
 'Moon with rainbow-like rings (lunar halo)' 'Cold weather' 'High heat'
 'Clear sky and visible stars'
 'Cloud (probably cumulus) without visible sky' 'Moderate Wind'
 'High intensity sun' 'Sunny with clouds'
 'Specific 7 stars (aligned) in the west with clouds'
 'Sharp moving clouds (cirrus) with visible stars'
 'Lightning with thunder' 'Small size moon (crescent moon)'
 'Thunder sounds / clouds moving East → West'
 'High intensity sunlight with clear sky' 'Clear sky'
 'Full moon with rings around it (Lunar Halo)' 'Light Wind' 'Dew present'
 'Heavy fog, which greatly obscures vision'
 'Full moon with rings of cloud (Lunar Halo)' 'Other']
Unique values in colums time_observed: is 9
[nan 'EVENING' 'ALL_DAY' 'AFTERNOON' 'EARLY_MORNING' 'NIGHT' 'MORNING'
 'DAWN' 'LATE_AFTERNOON']
Unique values in colums Target: is 4
['MEDIUMRAIN' 'HEAVYRAIN' 'SMALLRAIN' 'NORAIN']
Unique values in colums forecast_length: is 2
[12 24]

In [22]:
missing_columns = df.columns[df.isnull().any()].to_list()
for col in missing_columns:
    df[f"{col}_missing"] = df[col].isnull().astype(int)
    df[col] = df[col].fillna("missing")
df.head()

,confidence,predicted_intensity,community,district,prediction_time,indicator,indicator_description,time_observed,Target,forecast_length,indicator_missing,indicator_description_missing,time_observed_missing
user_id,,,,,,,,,,,,,
11,0.3,0.0,Tumfa,atiwa_west,2025-05-30 11:09:33,missing,missing,missing,MEDIUMRAIN,12,1,1,1
17,0.3,0.0,Kwabeng,atiwa_west,2025-05-30 11:09:35,missing,missing,missing,HEAVYRAIN,12,1,1,1
19,0.3,0.0,Akropong,atiwa_west,2025-05-30 11:09:47,missing,missing,missing,MEDIUMRAIN,12,1,1,1
23,0.3,0.0,Asamama,atiwa_west,2025-05-30 11:16:33,missing,missing,missing,HEAVYRAIN,12,1,1,1
23,0.3,0.0,Asamama,atiwa_west,2025-05-30 11:16:55,missing,missing,missing,HEAVYRAIN,12,1,1,1

In [23]:
df.isnull().any().any()

np.False_